name:                tube-roundel
version:             0.1.0.0
synopsis:            Web service for generating TfL Tube Roundels
description:         Please see README.md
homepage:            https://github.com/passy/tube-roundel#readme
license:             BSD3
author:              Pascal Hartig
maintainer:          phartig@rdrei.net
copyright:           2016 Pascal Hartig
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - base-compat
  - bytestring
  - http-media
  - rasterific-svg
  - servant
  - servant-server
  - template
  - directory
  - filepath
  - svg-tree
  - JuicyPixels
  - FontyFruity
  - text
  - wai
  - warp

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-record-updates
  - -fwarn-monomorphism-restriction
  - -fwarn-unused-do-bind

executables:
  tube-roundel:
    source-dirs:      src
    main:             Main.hs
